FROM almalinux:9
ARG course="DevOps with Docker" \
author="Matthews" \
company="inspiredevops"

RUN echo "Course: $course" && \
    echo "Author: $author" && \
    echo "Company: $company"
CMD ["sleep", "100"]
